<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\openrcs.ico</ApplicationIcon>
        <RootNamespace>OpenRCS</RootNamespace>
        <RuntimeIdentifiers>win-x64;osx-x64;osx-arm64;linux-x64</RuntimeIdentifiers>
        <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract Condition="'$(RuntimeIdentifier)' != ''">true</IncludeNativeLibrariesForSelfExtract>
        <!-- Only needed for the main executable project -->
        <PublishAot>true</PublishAot>

        <!-- Add to all projects/libraries in use, to ensure AOT compatibility -->
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
        <Content Include="Assets\openrcs.icns" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="Assets\openrcs.png" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../OpenRCS.Core/OpenRCS.Core.csproj"/>
        <PackageReference Include="Avalonia" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" Condition="'$(Configuration)' == 'Debug'">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
    </ItemGroup>
</Project>
