// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartSimulation() {
  return window['go']['simulation']['SimulationRuntime']['StartSimulation']();
}

export function SubmitCommand(arg1) {
  return window['go']['simulation']['SimulationRuntime']['SubmitCommand'](arg1);
}
