// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulation} from '../models';

export function StartSimulation():Promise<void>;

export function SubmitCommand(arg1:simulation.CommandRequest):Promise<boolean>;
