// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as layout$0 from "../layout/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as signaldiagram$0 from "../signal_diagram/models.js";

export interface Scenario {
    "id": ScenarioId;
    "name": string;
    "description": string;
    "railwayLayout": layout$0.RailwayLayout;
    "signallingDiagram": signaldiagram$0.SignalDiagram;
}

export type ScenarioId = string;
