// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from '@wailsio/runtime';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from '../service/models.js';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from '../state/models.js';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from './models.js';

export function GetCurrentScenario(): $CancellablePromise<$models.Scenario> {
	return $Call.ByID(2522019930);
}

export function GetScenarios(): $CancellablePromise<
	{ [_ in $models.ScenarioId]?: $models.Scenario } | null
> {
	return $Call.ByID(3174298170);
}

export function GetState(): $CancellablePromise<state$0.WorldState> {
	return $Call.ByID(2570170480);
}

export function NewRuntime(
	scenarioId: $models.ScenarioId
): $CancellablePromise<service$0.ApiError | null> {
	return $Call.ByID(2890237135, scenarioId);
}
