// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as layout$0 from "../layout/models.js";

export function GetLayouts(): $CancellablePromise<layout$0.RailwayLayoutId[] | null> {
    return $Call.ByID(3966199586);
}

export function NewRuntime(layout: layout$0.RailwayLayout): $CancellablePromise<void> {
    return $Call.ByID(2890237135, layout);
}
