// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as layout$0 from "../layout/models.js";

export interface DiagramPosition {
    "x": number;
    "y": number;
}

export interface DiagramSignal {
    "signalId": layout$0.SignalId;
    "diagramPosition": DiagramPosition;
    "orientation": number;
}

export interface DiagramSwitch {
    "switchId": layout$0.SwitchId;
    "diagramPosition": DiagramPosition;
}

export interface DiagramTrack {
    "diagramPositions": DiagramPosition[] | null;
    "trackCircuits": layout$0.TrackCircuitId[] | null;
}

export interface SignalDiagram {
    "tracks": DiagramTrack[] | null;
    "signals": DiagramSignal[] | null;
    "switches": { [_ in layout$0.SwitchId]?: DiagramSwitch } | null;
}
