// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * For service bindings
 */
export interface ApiError {
    "code": ErrorCode;
    "message": string;
}

export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LAYOUT_NOT_FOUND = "LAYOUT_NOT_FOUND",
    RUNTIME_NOT_FOUND = "RUNTIME_NOT_FOUND",
};
