// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EdgeEnd {
	NodeId: TrackNodeId;
	EdgeId: TrackEdgeId;
}

export enum NodeType {
	/**
	 * The Go zero value for the underlying type of the enum.
	 */
	$zero = '',

	NodeBoundary = 'boundary',

	/**
	 * Buffers/track ends
	 */
	NodeBuffer = 'buffer',

	/**
	 * Switches
	 */
	NodeSwitch = 'switch',

	/**
	 * Intersectings tracks
	 */
	NodeCrossing = 'crossing'
}

export interface Point {
	X: number;
	Y: number;
}

export interface RailwayLayout {
	TrackNodes: { [_ in TrackNodeId]?: TrackNode } | null;
	TrackEdges: { [_ in TrackEdgeId]?: TrackEdge } | null;
	Signals: { [_ in SignalId]?: Signal } | null;
	TrackCircuits: { [_ in TrackCircuitId]?: TrackCircuit } | null;
	Switches: { [_ in SwitchId]?: Switch } | null;
}

export interface Signal {
	/**
	 * Signals are placed at TrackNodes of boundary types only (two tracks connecting)
	 * Each signal is positioned at a node, so with an edge end we can use it to derive which direction the signal is facing in.
	 */
	Approach: EdgeEnd;
}

export type SignalId = string;

export interface Switch {
	Common: EdgeEnd;
	Normal: EdgeEnd;
	Reverse: EdgeEnd;
}

export type SwitchId = string;

export interface TrackCircuit {
	Edges: TrackEdgeId[] | null;
}

export type TrackCircuitId = string;

export interface TrackEdge {
	From: TrackNodeId;
	To: TrackNodeId;
	Geometry: Point[] | null;
	Properties: TrackProperties;
	AllowsToFrom: boolean;
	AllowsFromTo: boolean;
}

export type TrackEdgeId = string;

export interface TrackNode {
	Position: Point;
	Type: NodeType;
}

export type TrackNodeId = string;

export interface TrackProperties {
	Name: string;
	SpeedLimit: number;
	Electrified: boolean;
}
