// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EdgeEnd {
    "nodeId": TrackNodeId;
    "edgeId": TrackEdgeId;
}

export enum NodeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeBoundary = "boundary",

    /**
     * Buffers/track ends
     */
    NodeBuffer = "buffer",

    /**
     * Switches
     */
    NodeSwitch = "switch",

    /**
     * Intersectings tracks
     */
    NodeCrossing = "crossing",
};

export interface Point {
    "x": number;
    "y": number;
}

export interface RailwayLayout {
    "trackNodes": { [_ in TrackNodeId]?: TrackNode } | null;
    "trackEdges": { [_ in TrackEdgeId]?: TrackEdge } | null;
    "signals": { [_ in SignalId]?: Signal } | null;
    "trackCircuits": { [_ in TrackCircuitId]?: TrackCircuit } | null;
    "switches": { [_ in SwitchId]?: Switch } | null;
}

export interface Signal {
    /**
     * Signals are placed at TrackNodes of boundary types only (two tracks connecting)
     * Each signal is positioned at a node, so with an edge end we can use it to derive which direction the signal is facing in.
     */
    "approach": EdgeEnd;
}

export type SignalId = string;

export interface Switch {
    "common": EdgeEnd;
    "normal": EdgeEnd;
    "reverse": EdgeEnd;
}

export type SwitchId = string;

export interface TrackCircuit {
    "edges": TrackEdgeId[] | null;
}

export type TrackCircuitId = string;

export interface TrackEdge {
    "From": TrackNodeId;
    "To": TrackNodeId;
    "Geometry": Point[] | null;
    "Properties": TrackProperties;
    "AllowsToFrom": boolean;
    "AllowsFromTo": boolean;
}

export type TrackEdgeId = string;

export interface TrackNode {
    "Position": Point;
    "Type": NodeType;
}

export type TrackNodeId = string;

export interface TrackProperties {
    "name": string;
    "speedLimit": number;
    "electrified": boolean;
}
