// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RailwayLayout {
	Tracks: { [_ in TrackId]?: Track | null } | null;
	Signals: { [_ in SignalId]?: Signal | null } | null;
	TrackCircuits: { [_ in TrackCircuitId]?: TrackCircuit | null } | null;
	Switches: { [_ in SwitchId]?: Switch | null } | null;
}

export type RailwayLayoutId = string;

export interface Signal {
	Protects: TrackCircuitId[] | null;
	Position: TrackPosition;
}

export type SignalId = string;

export interface Switch {
	Common: TrackEndpoint;
	Normal: TrackEndpoint;
	Reverse: TrackEndpoint;
}

export type SwitchId = string;

export interface Track {
	Length: number;
}

export interface TrackCircuit {
	StartPosition: TrackPosition;
	EndPosition: TrackPosition;
}

export type TrackCircuitId = string;

export enum TrackEnd {
	/**
	 * The Go zero value for the underlying type of the enum.
	 */
	$zero = 0,

	Start = 0,
	End = 1
}

export interface TrackEndpoint {
	TrackId: TrackId;
	Endpoint: TrackEnd;
}

export type TrackId = string;

export interface TrackPosition {
	TrackId: TrackId;
	Offset: number;
}
