// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getLayouts: () => __TAURI_INVOKE<Scenario[]>("get_layouts"),
};

/* Types */
export type DiagramPosition = {
	x: number | null,
	y: number | null,
};

export type DiagramSignal = {
	signal_id: string,
	position: DiagramPosition,
};

export type DiagramSwitch = {
	switch_id: string,
	position: DiagramPosition,
};

export type DiagramTrack = {
	positions: DiagramPosition[],
	track_circuits: string[],
};

export type EdgeEnd = {
	node_id: string,
	edge_id: string,
};

export type Point = {
	x: number | null,
	y: number | null,
};

export type Scenario = {
	id: string,
	name: string,
	description: string,
	layout: SimulationLayout,
	diagram: SignalDiagram,
};

export type Signal = {
	approach: EdgeEnd,
};

export type SignalDiagram = {
	tracks: DiagramTrack[],
	signals: DiagramSignal[],
	switches: { [key in string]: DiagramSwitch },
};

export type SimulationLayout = {
	track_circuits: { [key in string]: TrackCircuit },
	signals: { [key in string]: Signal },
	track_nodes: { [key in string]: TrackNode },
	track_edges: { [key in string]: TrackEdge },
	switches: { [key in string]: Switch },
};

export type Switch = {
	common: EdgeEnd,
	normal: EdgeEnd,
	reverse: EdgeEnd,
};

export type TrackCircuit = {
	edges: string[],
};

export type TrackEdge = {
	from: string,
	to: string,
	geometry: Point[],
	properties: TrackProperties,
	allows_from_to: boolean,
	allows_to_from: boolean,
};

export type TrackNode = {
	position: Point,
	track_type: TrackType,
};

export type TrackProperties = {
	electrified: boolean,
	speed_limit: number,
};

export type TrackType = "Boundary" | "Buffer" | "Switch" | "Crossing";

